<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_M17N_CONFIGURATION_STATUS_DEFAULT',     'true');
define('MODULE_M17N_CONFIGURATION_SORT_ORDER_DEFAULT', '');

define('MODULE_M17N_CONFIGURATION_NAME_DEFAULT', 'm17n');
define('MODULE_M17N_CONFIGURATION_VALUE_DEFAULT', 'configuration');

define('MODULE_M17N_CONFIGURATION_PRODUCT_TYPE_LAYOUT_PREFIX', 'PTL_');
define('MODULE_M17N_CONFIGURATION_MODULE_PREFIX', 'MOD_');
define('MODULE_M17N_CONFIGURATION_ADDON_MODULE_PREFIX', 'ADMOD_');
?>