<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_FEATURE_AREA_STATUS_DEFAULT', 'true');
define('MODULE_FEATURE_AREA_SORT_ORDER_DEFAULT', '');

define('MODULE_FEATURE_AREA_UI_MAX_DISPLAY_DEFAULT', 8);
define('MODULE_FEATURE_AREA_UI_CONF_AUTO_DEFAULT', 6200);
define('MODULE_FEATURE_AREA_UI_CONF_SPEED_DEFAULT', 800);
define('MODULE_FEATURE_AREA_UI_CONF_VISIBLE_DEFAULT', 5);
define('MODULE_FEATURE_AREA_UI_CONF_CIRCULAR', 'true');
define('MODULE_FEATURE_AREA_UI_CONF_SCROLL', 1);

?>