<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_MULTIPLE_IMAGE_VIEW_STATUS_DEFAULT', 'true');
define('MODULE_MULTIPLE_IMAGE_VIEW_SORT_ORDER_DEFAULT', '');
define('MODULE_MULTIPLE_IMAGE_VIEW_THMB_WIDTH_DEFAULT', SMALL_IMAGE_WIDTH);
define('MODULE_MULTIPLE_IMAGE_VIEW_THMB_HEIGHT_DEFAULT', SMALL_IMAGE_HEIGHT);
?>