<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_EASY_ADMIN_STATUS_DEFAULT',     'true');
define('MODULE_EASY_ADMIN_SORT_ORDER_DEFAULT', '');
define('MODULE_EASY_ADMIN_DASHBOARD_REDIRECT_URL_DEFAULT', zen_href_link((defined(FILENAME_SUPER_ORDERS) ? FILENAME_SUPER_ORDERS : FILENAME_ORDERS),'','SSL'));
?>
