<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_ADDON_MODULES_ADVANCED_STOCK_STATUS_DEFAULT', 'true');
define('MODULE_ADDON_MODULES_ADVANCED_STOCK_SORT_ORDER_DEFAULT', '100');
define('MODULE_ADDON_MODULES_ADVANCED_STOCK_DISPLAY_STOCK_DEFAULT', 'true');
define('MODULE_ADDON_MODULES_COLUMN_NAME', 'send_for_status');
?>