<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_ADDON_MODULES_CATEGORY_SITEMAP_STATUS_DEFAULT',     'true');
define('MODULE_ADDON_MODULES_CATEGORY_SITEMAP_TREE_LEVEL_DEFAULT', '2');
define('MODULE_ADDON_MODULES_CATEGORY_SITEMAP_SORT_ORDER_DEFAULT', '');
?>