<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
// csv definition
define('MODULE_PRODUCT_CSV_STATUS_DEFAULT', 'true');
define('MODULE_PRODUCT_CSV_SORT_ORDER_DEFAULT', '');

define('MODULE_PRODUCT_CSV_IMPORT_CHARACTER', 'SJIS-win,eucJP-win,UTF-8,ASCII,JIS');
define('MODULE_PRODUCT_CSV_INTERNAL_CHARACTER', 'eucJP-win');
define('MODULE_PRODUCT_CSV_EXPORT_CHARACTER', 'SJIS-win');

define('MODULE_PRODUCT_CSV_FORMAT_COLUMN_IGNORE', 'ignore');
define('MODULE_PRODUCT_CSV_FORMAT_COLUMN_DELETE', 'delete');
define('MODULE_PRODUCT_CSV_PREFERRED_LANGUAGE_ID', 2);

// csv export
define('MODULE_PRODUCT_CSV_EXPORT_CONFIG_SEP', ',');
define('MODULE_PRODUCT_CSV_EXPORT_CONFIG_QUOTE', '"');
define('MODULE_PRODUCT_CSV_EXPORT_CONFIG_EOL', "\r\n");

// date
define('MODULE_PRODUCT_CSV_EXPORT_DATE_DEFAULT', '0001-01-01');
define('MODULE_PRODUCT_CSV_EXPORT_DATE_ZERO', '0000-00-00');
define('MODULE_PRODUCT_CSV_EXPORT_DATETIME_DEFAULT', '0001-01-01 00:00:00');
define('MODULE_PRODUCT_CSV_EXPORT_DATETIME_ZERO', '0000-00-00 00:00:00');
?>
