<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_ABOUTBOX_STATUS_DEFAULT', 'true');
define('MODULE_ABOUTBOX_SORT_ORDER_DEFAULT', '');
define('MODULE_ABOUTBOX_HEADER_DEFAULT', '');
define('MODULE_ABOUTBOX_IMAGEPATH_DEFAULT', 'images/my.png');
define('MODULE_ABOUTBOX_DISPLAY_CALENDAR_DEFAULT', 'true');
define('MODULE_ABOUTBOX_AVAILABLE_PAYMENT_DEFAULT','true');
define('MODULE_ABOUTBOX_AVALABLE_CARDS_DEFAULT', '2');