<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_ABOUTBOX_STATUS_DEFAULT', 'true');
define('MODULE_ABOUTBOX_SORT_ORDER_DEFAULT', '');
define('MODULE_ABOUTBOX_HEADER_DEFAULT', '');
define('MODULE_ABOUTBOX_IMAGEPATH_DEFAULT', 'images/my.png');
define('MODULE_ABOUTBOX_DISPLAY_CALENDAR_DEFAULT', 'true');
define('MODULE_ABOUTBOX_AVAILABLE_PAYMENT_DEFAULT','true');
define('MODULE_ABOUTBOX_AVALABLE_CARDS_DEFAULT', '2');

// installÍÑ
define('MODULE_ABOUTBOX_CFG_HEADER_DEFAULT_JA', '');
define('MODULE_ABOUTBOX_CFG_HEADER_DEFAULT_EN', '');
define('MODULE_ABOUTBOX_GREETING_TITLE_DEFAULT_JA', 'Å¹Ä¹¤«¤é¤Î°§»¢');
define('MODULE_ABOUTBOX_GREETING_TITLE_DEFAULT_EN', 'Greetings from the shop master');
define('MODULE_ABOUTBOX_GREETING_TEXT_DEFAULT_JA', 'Å¹Ä¹¤Î¡û¡û¡û¤Ç¤¹¡£');
define('MODULE_ABOUTBOX_GREETING_TEXT_DEFAULT_EN', 'I\'m John Smith,the shop master.');

define('MODULE_ABOUTBOX_CFG_HEADER_DEFAULT', zen_m17n_serialize_value(array('ja' => MODULE_ABOUTBOX_CFG_HEADER_DEFAULT_JA, 'en' => MODULE_ABOUTBOX_CFG_HEADER_DEFAULT_EN)));
define('MODULE_ABOUTBOX_GREETING_TITLE_DEFAULT', zen_m17n_serialize_value(array('ja' => MODULE_ABOUTBOX_GREETING_TITLE_DEFAULT_JA,'en' => MODULE_ABOUTBOX_GREETING_TITLE_DEFAULT_EN)));
define('MODULE_ABOUTBOX_GREETING_TEXT_DEFAULT', zen_m17n_serialize_value(array('ja' => MODULE_ABOUTBOX_GREETING_TEXT_DEFAULT_JA,'en' => MODULE_ABOUTBOX_GREETING_TEXT_DEFAULT_EN)));

?>
