<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}

define('MODULE_FACEBOOK_OGP_STATUS_DEFAULT', 'true');
define('MODULE_FACEBOOK_OGP_SORT_ORDER_DEFAULT', '');

define('MODULE_FACEBOOK_OGP_USER_IDS_DEFAULT', '');
define('MODULE_FACEBOOK_OGP_OG_EMAIL_DEFAULT', '');
define('MODULE_FACEBOOK_OGP_OG_PHONE_NUMBER_DEFAULT', '');
define('MODULE_FACEBOOK_OGP_OG_FAX_NUMBER_DEFAULT', '');
?>
