<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_PRODUCTS_WITH_ATTRIBUTES_STOCK_STATUS_DEFAULT',     'true');
define('MODULE_PRODUCTS_WITH_ATTRIBUTES_STOCK_SORT_ORDER_DEFAULT', '');
