<?php
/**
 * Module Configuration Settings
 *
 * @package Addon Modules
 * @copyright Copyright (C) 2009 Liquid System Technology, Inc.
 * @author Koji Sasaki
 * @copyright Portions Copyright 2003-2005 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: configure.php $
 */
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}

define('MODULE_CAROUSEL_UI_STATUS_DEFAULT', 'true');
define('MODULE_CAROUSEL_UI_JCAROUSELLITE_LIBRARY_DEFAULT', 'jcarousellite_1.0.1_acc.js');
define('MODULE_CAROUSEL_UI_SORT_ORDER_DEFAULT', MODULE_JQUERY_SORT_ORDER + 10);

define('MODULE_CAROUSEL_UI_MAX_DISPLAY_NEW_PRODUCTS_DEFAULT', 4);
define('MODULE_CAROUSEL_UI_CONF_AUTO_NEW_PRODUCTS_DEFAULT', 0);
define('MODULE_CAROUSEL_UI_CONF_SPEED_NEW_PRODUCTS_DEFAULT', 200);
define('MODULE_CAROUSEL_UI_CONF_VERTICAL_NEW_PRODUCTS_DEFAULT', 'false');
define('MODULE_CAROUSEL_UI_CONF_CIRCULAR_NEW_PRODUCTS_DEFAULT', 'true');
define('MODULE_CAROUSEL_UI_CONF_VISIBLE_NEW_PRODUCTS_DEFAULT', 3);
define('MODULE_CAROUSEL_UI_CONF_SCROLL_NEW_PRODUCTS_DEFAULT', 1);

define('MODULE_CAROUSEL_UI_MAX_DISPLAY_FEATURED_PRODUCTS_DEFAULT', 4);
define('MODULE_CAROUSEL_UI_CONF_AUTO_FEATURED_PRODUCTS_DEFAULT', 0);
define('MODULE_CAROUSEL_UI_CONF_SPEED_FEATURED_PRODUCTS_DEFAULT', 200);
define('MODULE_CAROUSEL_UI_CONF_VERTICAL_FEATURED_PRODUCTS_DEFAULT', 'false');
define('MODULE_CAROUSEL_UI_CONF_CIRCULAR_FEATURED_PRODUCTS_DEFAULT', 'true');
define('MODULE_CAROUSEL_UI_CONF_VISIBLE_FEATURED_PRODUCTS_DEFAULT', 3);
define('MODULE_CAROUSEL_UI_CONF_SCROLL_FEATURED_PRODUCTS_DEFAULT', 1);

define('MODULE_CAROUSEL_UI_MAX_DISPLAY_SPECIALS_PRODUCTS_DEFAULT', 4);
define('MODULE_CAROUSEL_UI_CONF_AUTO_SPECIALS_PRODUCTS_DEFAULT', 0);
define('MODULE_CAROUSEL_UI_CONF_SPEED_SPECIALS_PRODUCTS_DEFAULT', 200);
define('MODULE_CAROUSEL_UI_CONF_VERTICAL_SPECIALS_PRODUCTS_DEFAULT', 'false');
define('MODULE_CAROUSEL_UI_CONF_CIRCULAR_SPECIALS_PRODUCTS_DEFAULT', 'true');
define('MODULE_CAROUSEL_UI_CONF_VISIBLE_SPECIALS_PRODUCTS_DEFAULT', 3);
define('MODULE_CAROUSEL_UI_CONF_SCROLL_SPECIALS_PRODUCTS_DEFAULT', 1);

define('MODULE_CAROUSEL_UI_MAX_DISPLAY_ALSO_PURCHASED_PRODUCTS_DEFAULT', 4);
define('MODULE_CAROUSEL_UI_CONF_AUTO_ALSO_PURCHASED_PRODUCTS_DEFAULT', 0);
define('MODULE_CAROUSEL_UI_CONF_SPEED_ALSO_PURCHASED_PRODUCTS_DEFAULT', 200);
define('MODULE_CAROUSEL_UI_CONF_VERTICAL_ALSO_PURCHASED_PRODUCTS_DEFAULT', 'false');
define('MODULE_CAROUSEL_UI_CONF_CIRCULAR_ALSO_PURCHASED_PRODUCTS_DEFAULT', 'true');
define('MODULE_CAROUSEL_UI_CONF_VISIBLE_ALSO_PURCHASED_PRODUCTS_DEFAULT', 3);
define('MODULE_CAROUSEL_UI_CONF_SCROLL_ALSO_PURCHASED_PRODUCTS_DEFAULT', 1);

define('MODULE_CAROUSEL_UI_MAX_DISPLAY_XSELL_PRODUCTS_DEFAULT', 4);
define('MODULE_CAROUSEL_UI_CONF_AUTO_XSELL_PRODUCTS_DEFAULT', 0);
define('MODULE_CAROUSEL_UI_CONF_SPEED_XSELL_PRODUCTS_DEFAULT', 200);
define('MODULE_CAROUSEL_UI_CONF_VERTICAL_XSELL_PRODUCTS_DEFAULT', 'false');
define('MODULE_CAROUSEL_UI_CONF_CIRCULAR_XSELL_PRODUCTS_DEFAULT', 'true');
define('MODULE_CAROUSEL_UI_CONF_VISIBLE_XSELL_PRODUCTS_DEFAULT', 3);
define('MODULE_CAROUSEL_UI_CONF_SCROLL_XSELL_PRODUCTS_DEFAULT', 1);
