<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_VIEWED_PRODUCTS_STATUS_DEFAULT', 'true');
define('MODULE_VIEWED_PRODUCTS_MAX_DISPLAY_VIEWED_DEFAULT', 10);
define('MODULE_VIEWED_PRODUCTS_SMALL_IMAGE_SIZE_DEFAULT', '80x80');
define('MODULE_VIEWED_PRODUCTS_SORT_ORDER_DEFAULT', '');
