<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_POINT_BASE_STATUS_DEFAULT', 'false');
define('MODULE_POINT_BASE_POINT_SYMBOL_DEFAULT', 'point');
define('MODULE_POINT_BASE_MAX_DISPLAY_SEARCH_RESULTS_POINTS_DEFAULT', '20');
define('MODULE_POINT_BASE_SORT_ORDER_DEFAULT', '');
