<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_POINT_CREATEACCOUNT_STATUS_DEFAULT', 'false');
define('MODULE_POINT_CREATEACCOUNT_PENDING_DEFAULT', 'false');
define('MODULE_POINT_CREATEACCOUNT_POINT_DEFAULT', '');
define('MODULE_POINT_CREATEACCOUNT_SORT_ORDER_DEFAULT', '');
