<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_EASY_REVIEWS_STATUS_DEFAULT', 'true');
define('MODULE_EASY_REVIEWS_SORT_ORDER_DEFAULT', '');
define('MODULE_EASY_REVIEWS_MAX_DISPLAY_NEW_REVIEWS_DEFAULT', '3');
define('MODULE_EASY_REVIEWS_LIST_DISPLAY_FORCE_LOGIN_DEFAULT', 'false');
?>