<?php
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}
define('MODULE_EMAIL_TEMPLATES_STATUS_DEFAULT', 'true');
define('MODULE_EMAIL_TEMPLATES_SORT_ORDER_DEFAULT', '');

define('MODULE_EMAIL_TEMPLATE_CREATE_ACCOUNT_MAIL_ID', '1');
define('MODULE_EMAIL_TEMPLATE_CHECKOUT_SUCCESS_MAIL_ID', '2');
define('MODULE_EMAIL_TEMPLATE_CHECKOUT_SUCCESS_VISITOR_MAIL_ID', '3');
define('MODULE_EMAIL_TEMPLATE_STATUS_MAIL_ID', '4');
?>